package net.sourceforge.dscsim.controller.message.types;
// Generated 08.02.2008 17:23:08 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CodeText generated by hbm2java
 */
@Entity
@Table(name="CODE_TEXT"
    , uniqueConstraints = {  }
)
public class CodeText  implements java.io.Serializable {

    // Fields    

     private String code;
     private String text;
     private Set<AddressBook> addressBooks = new HashSet<AddressBook>(0);

     // Constructors

    /** default constructor */
    public CodeText() {
    }

	/** minimal constructor */
    public CodeText(String code) {
        this.code = code;
    }
    /** full constructor */
    public CodeText(String code, String text, Set<AddressBook> addressBooks) {
       this.code = code;
       this.text = text;
       this.addressBooks = addressBooks;
    }
   
    // Property accessors
     @Id
    
    @Column(name="CODE", unique=true, nullable=false, insertable=true, updatable=true, length=2)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="TEXT", unique=false, nullable=true, insertable=true, updatable=true, length=32)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="codeText")
    public Set<AddressBook> getAddressBooks() {
        return this.addressBooks;
    }
    
    public void setAddressBooks(Set<AddressBook> addressBooks) {
        this.addressBooks = addressBooks;
    }




}


