CREATE TABLE CODE_TEXT ( 
CODE CHAR(2) PRIMARY KEY, 
TEXT CHAR(32)
);

CREATE TABLE ADDRESS_BOOK (
ID CHAR(9) PRIMARY KEY,
NAME CHAR(15), 
TYPE_CD CHAR(2)
);


CREATE TABLE DSCMESSAGE (
UID TIMESTAMP,
SENDER CHAR(9), 
RECIPIENT CHAR(9) NULL, 
CALL_TYPE_CD CHAR(32),
NATURE_CD CHAR(32) , 
CATAGORY_CD CHAR(32),  
POS_LAT_DEG INT,
POS_LAT_MIN INT,
POS_LAT_HEM CHAR(1),
POS_LON_DEG INT,
POS_LON_MIN INT,
POS_LON_HEM CHAR(1),
POS_TIME_HRS INT,
POS_TIME_MIN INT,
CHANNEL INT,
COMPLIANCE_CD CHAR(32),
COMPLIANCE_REASON_CD CHAR(32),
ACKD_TIME TIMESTAMP,
PRIMARY KEY(UID, SENDER)

);

CREATE TABLE  DSCATTR (
CLASS CHAR(4),
ATTR_NAME CHAR(12),
ATTR_VALUE CHAR(32)
);

CREATE VIEW GPS_SETTINGS (LATDEG, LATMIN, LONDEG, LONMIN, HRS, MIN)
AS SELECT ATTR_VALUE,


INSERT INTO DSCATTR (CLASS, ATTR_NAME, ATTR_VALUE)
VALUES ('GPS_POS', 'LATDEG', '42')


CREATE VIEW POSITION_SETTING AS
SELECT 
	A.ATTR_VALUE AS LAT_DEG,
	B.ATTR_VALUE AS LAT_MIN,
	C.ATTR_VALUE AS LON_DEG,
	D.ATTR_VALUE AS LON_MIN
FROM
	DSCATTR A,
	DSCATTR B, 
	DSCATTR C,
	DSCATTR D
WHERE 
	A.CLASS = B.CLASS 
	AND A.CLASS = C.CLASS
	AND A.CLASS = D.CLASS
	AND A.ATTR_NAME = 'LATDEG'
	AND B.ATTR_NAME = 'LATMIN'
	AND C.ATTR_NAME = 'LONDEG'
	AND D.ATTR_NAME = 'LONMIN'



CREATE VIEW TIME_SETTING AS
SELECT 
A.ATTR_VALUE AS HOURS,
B.ATTR_VALUE AS MINUTES
FROM
DSCATTR A,
DSCATTR B
 WHERE A.CLASS = B.CLASS
AND A.ATTR_NAME = 'HRS'
AND B.ATTR_NAME = 'MIN'






