//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.22 at 05:59:05 PM CET 
//


package net.sourceforge.dscsim.controller.settings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.sourceforge.dscsim.controller.settings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Infostore_QNAME = new QName("http://dscsim.sourceforge.net/controller/settings", "infostore");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sourceforge.dscsim.controller.settings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InfoStoreType }
     * 
     */
    public InfoStoreType createInfoStoreType() {
        return new InfoStoreType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoStoreType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dscsim.sourceforge.net/controller/settings", name = "infostore")
    public JAXBElement<InfoStoreType> createInfostore(InfoStoreType value) {
        return new JAXBElement<InfoStoreType>(_Infostore_QNAME, InfoStoreType.class, null, value);
    }

}
