//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.22 at 05:59:05 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dscsim.sourceforge.net/controller/settings", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.sourceforge.dscsim.controller.settings;
