package net.sourceforge.dscsim.controller.message.types;
// Generated 08.02.2008 17:23:08 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AddressBook generated by hbm2java
 */
@Entity
@Table(name="ADDRESS_BOOK"
    , uniqueConstraints = {  }
)
public class AddressBook  implements java.io.Serializable {

    // Fields    

     private String mmsi;
     private CodeText codeText;
     private String id;

     // Constructors

    /** default constructor */
    public AddressBook() {
    }

	/** minimal constructor */
    public AddressBook(String mmsi) {
        this.mmsi = mmsi;
    }
    /** full constructor */
    public AddressBook(String mmsi, CodeText codeText, String id) {
       this.mmsi = mmsi;
       this.codeText = codeText;
       this.id = id;
    }
   
    // Property accessors
     @Id
    
    @Column(name="MMSI", unique=true, nullable=false, insertable=true, updatable=true, length=9)
    public String getMmsi() {
        return this.mmsi;
    }
    
    public void setMmsi(String mmsi) {
        this.mmsi = mmsi;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="TYPE_CD", unique=false, nullable=true, insertable=true, updatable=true)
    public CodeText getCodeText() {
        return this.codeText;
    }
    
    public void setCodeText(CodeText codeText) {
        this.codeText = codeText;
    }
    
    @Column(name="ID", unique=false, nullable=true, insertable=true, updatable=true, length=15)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }




}


