/*
 * SetupDialog.java
 *
 * Created on 12. September 2006, 21:10
 */

package net.sourceforge.dscsim.controller;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Properties;

import javax.swing.JCheckBox;
import javax.swing.JDialog;

import net.sourceforge.dscsim.controller.message.types.Latitude;
import net.sourceforge.dscsim.controller.message.types.Longitude;
import net.sourceforge.dscsim.controller.utils.AppLogger;




/**
 *
 * @author  katharina
 */
public class SetupSimulationDialog extends  JDialog implements ActionListener, Constants {
    
	private InstanceContext _oCtx = null;
	
    /** Creates new form SetupDialog */
    public SetupSimulationDialog(java.awt.Frame parent, InstanceContext oCtx) {
        super(parent, true);
        _oCtx = oCtx;
		setSize(DEF_DIALOG_WIDTH,DEF_DIALOG_HEIGHT); 
        initComponents();

    }
    
    /** This method is called from within the constructor to
      * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
    	
    		setTitle("Simulation Settings");
    		_cpySettings = (Properties)MultiContentManager.getAppSettings().clone();
   
        cbGps = new JCheckBox();
        cbGps.setBounds(10, 15, 100, 20);
        cbGps.setText("GPS");
        cbGps.setToolTipText("Check to activate GPS device.");
        getContentPane().add(cbGps);
        
        String bGps = MultiContentManager.getAppSettings().getProperty(SETUP_GPS);       
        cbGps.setSelected(!Boolean.valueOf(bGps).booleanValue());

        cbGps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doGpsActionPerformed(evt);
            }
        });

 
        getContentPane().setLayout(null);

        jButnOK = new javax.swing.JButton();
        jButnOK.setActionCommand(AWT_OK);
        
        jButnCncl = new javax.swing.JButton();
        jButnCncl.setActionCommand(AWT_CAN);
 
        jButnOK.setText("OK");
        getContentPane().add(jButnOK);
        jButnOK.setBounds(110, 180, 75, 29);

        jButnCncl.setText("Cancel");
        getContentPane().add(jButnCncl);
        jButnCncl.setBounds(240, 180, 75, 29);
        
        jButnOK.addActionListener(this);
        jButnCncl.addActionListener(this);        
               

    }

    private void doGpsActionPerformed(java.awt.event.ActionEvent evt) {   		    		
    		_cpySettings.put(SETUP_GPS, Boolean.valueOf(!cbGps.isSelected()).toString());   		   		
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {        	 
        setVisible(false);
        dispose();
    }                            
    

    
    
    // Variables declaration - do not modify
    private javax.swing.JButton jButnOK;
    private javax.swing.JButton jButnCncl;
    private javax.swing.JCheckBox cbGps;
    private Properties _cpySettings = null;
    
    // End of variables declaration
	public void actionPerformed(ActionEvent e) {
			
		if(e.getActionCommand().equals(AWT_OK)){
    			MultiContentManager.storeAppSettings(_cpySettings); 
    			
    			//clear the position and time entries.
    			
    			if(cbGps.isSelected() == false){
 
    	   			MultiContentManager oMngr = _oCtx.getContentManager();
        			
        			try{
            			//oMngr.resetProperty("Longitude");
            			//oMngr.resetProperty("Latitude");
            			//oMngr.resetProperty("Time");
            			//oMngr.saveProperties();
    		       		//DscString mode = new DscString("POS_MNL");
    		       	   	//oMngr.getSetting("PositionType").setValue(mode);		
   				
        			}catch(Exception oEx){
        				AppLogger.error(oEx);
        			}
     
    			} else {
       	   			MultiContentManager oMngr = _oCtx.getContentManager();
       	   		
		       	   	try{
			       	   	Longitude lon = new Longitude(72, 30, Longitude.Hemisphere.W);
			       	   	//oMngr.setSetting("Longitude", lon);
	        
			       	   	Latitude lat = new Latitude(42, 15, Latitude.Hemisphere.N);
			       	   	//oMngr.setSetting("Latitude", lat);
	
			       	   	//Time time = new Time("12", "30");
			       	   	//oMngr.setSetting("Time", time);
			       	   	
			       		//DscString mode = new DscString("POS_GPS");
			       	   	//oMngr.setSetting("PositionType", mode);		
		       	   		
		       	   	}catch(Exception oEx){
						AppLogger.error(oEx);
					}
    				
    			}
    		
  	   		MultiContentManager oMngr = _oCtx.getContentManager();
  	   		//oMngr.saveProperties();
  	   		    			
    			closeDialog(null);
    	
    			_oCtx.getBus().publish(new BusMessage(this, BTN_RESET));

		} else if(e.getActionCommand().equals(AWT_CAN)){     
			closeDialog(null);
		} 
		
	}
	
    
}
