/*
 * Created on 16.12.2006
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package net.sourceforge.dscsim.controller;

import java.awt.Rectangle;

import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JTextArea;

import net.sourceforge.dscsim.controller.utils.AppLogger;




import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

/**
 * @author Administrator
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
public class StartupConfiguration extends JDialog implements ActionListener, Constants {

    // Variables declaration - do not modify
    private javax.swing.JButton jButnOK;
    private javax.swing.JButton jButnCncl;
    private String cfgFile = null;
    private JTextField keyFld = null;
    private Properties installProps = null;
    
    private String _exitEvent = "";
    
    private String setupFile = "setup/windows/setup.properties";
    
  
	public StartupConfiguration(){
		setSize(DEF_DIALOG_WIDTH,DEF_DIALOG_HEIGHT); 
		 
		this.initComponents();
  		
	}
	
	public boolean okPressed(){
		return  AWT_OK.equals(_exitEvent);
	}
    // End of variables declaration
	public void actionPerformed(ActionEvent e) {
						
		if(e.getActionCommand().equals(AWT_OK)){
			_exitEvent = AWT_OK;
			try {
				FileOutputStream fos = new FileOutputStream(cfgFile);
	
				String str = keyFld.getText().trim();
				
				fos.write(str.getBytes());
				
				fos.close();
			
			} catch (FileNotFoundException oEx) {
				AppLogger.error(oEx);
			} catch(IOException oEx){
				AppLogger.error(oEx);
			}
		
		}
		
		closeDialog(null);
	}

	public void setCfgFile(String v){
		cfgFile = v;
	}
	public static void main(String[] args) {
		
		StartupConfiguration oDlg = new StartupConfiguration();
		
		oDlg.cfgFile = args[0];
		
		if(args[1]!= null)
			oDlg.setupFile = args[1];
			
		oDlg.show();
	}
	
    private void addField(){
    	
       	int  x=10, y=140, width=420, height=20;  	
     	Rectangle rec = new Rectangle(x, y, width, height);
    	
    	keyFld = new javax.swing.JTextField();
        getContentPane().add(keyFld);
        keyFld.setBounds(rec.x, rec.y, rec.width, rec.height);
    	
        JTextArea infoText = new JTextArea();
    	infoText.setEditable(false);
    	infoText.setLineWrap(true);
    	infoText.setWrapStyleWord(true);
    	infoText.setFocusable(false);
    	infoText.setText(getProperties().getProperty("instructions.key"));
    	getContentPane().add(infoText);
    	infoText.setBounds(10, 10, width, 120);
    	
		
    }
    
    private synchronized Properties getProperties(){
    	
    	if(installProps == null){
    		
    		installProps = new Properties();
  	
				try {
					FileInputStream in = new FileInputStream(setupFile);
					
					installProps.load(in);
				} catch (FileNotFoundException oEx) {
					AppLogger.error(oEx);
				} catch (IOException oEx) {
					AppLogger.error(oEx);
				}
				
				
		}
			
    	return installProps;
    	
    }
    
    /** This method is called from within the constructor to
      * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
    	
    	this.setTitle("Configure Startup");
    	
        getContentPane().setLayout(null);


       	//dscsim.provider.protocol=%3 dscsim.provider.user=%4 dscsim.provider.pwd=%5 dscsim.provider.url=%6
    	addField();
 
        jButnOK = new javax.swing.JButton();
        jButnOK.setActionCommand(AWT_OK);
        
        jButnCncl = new javax.swing.JButton();
        jButnCncl.setActionCommand(AWT_CAN);
 
        jButnOK.setText("OK");
        getContentPane().add(jButnOK);
        jButnOK.setBounds(110, 180, 75, 29);

        jButnCncl.setText("Cancel");
        getContentPane().add(jButnCncl);
        jButnCncl.setBounds(240, 180, 75, 29);
        
        jButnOK.addActionListener(this);
        jButnCncl.addActionListener(this);        
     
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {        	 
        setVisible(false);
        dispose();
    } 
}
